source 'https://rubygems.org'

gem 'fluentd', '~>1.3.1'
gem 'activesupport', '~>5.2.2'
gem 'oj', '~>3.7.4'

# Input / Output plugins:
gem 'fluent-plugin-systemd', '~>1.0.1'
gem 'fluent-plugin-elasticsearch', '~>2.12.3'
gem 'fluent-plugin-prometheus', '~>1.2.1'
gem 'fluent-plugin-splunk-enterprise', '~> 0.9.1'
gem 'fluent-plugin-kafka', '~> 0.8.1'
gem 'fluent-plugin-detect-exceptions', '~>0.0.11'
gem 'fluent-plugin-kubernetes_metadata_filter', '~>2.0.0'
gem 'fluent-plugin-secure-forward', '~> 0.4.5'
gem 'fluent-plugin-remote_syslog_tls', '~> 1.0.2'
gem 'fluent-plugin-record-reformer', '~> 0.9.1'
gem 'fluent-plugin-kinesis', '~> 2.1.1'
gem 'fluent-plugin-s3', '~> 1.1.7'

# filter plugins
gem 'fluent-plugin-rewrite-tag-filter', '~> 2.1.1'
gem 'fluent-plugin-record-modifier', '~> 1.1.0'
gem 'fluent-plugin-concat', '~> 2.3.0'
gem 'fluent-plugin-fields-parser', '~> 0.1.2'

# parser plugins
gem 'fluent-plugin-grok-parser', '~>2.4.0'
gem 'fluent-plugin-multi-format-parser', '~>1.0.0'

# formatter plugins
gem 'fluent-plugin-formatter_sprintf', '~>0.1.0'
